version: "3.9"

services:
  agent:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-container
    volumes:
      - .:/app
    networks:
      - nrm_app_nrm_backend

networks:
  nrm_app_nrm_backend:
    external: true
