version: "3.9"

services:
  agent:
    image: agent_image:1.0
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-container
    ports:
      - "445:445"
      - "5005:5005"
    volumes:
      - .:/app
      - /srv/samba/public:/mnt/c/Users/Diego/PycharmProjects/inz_app/test_samby
#    networks:
#      - nrm_app_nrm_backend
    network_mode: host


#networks:
#  nrm_app_nrm_backend:
#    external: true
