version: "3.9"

services:
  agent:
    image: agent_image:1.0
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-container
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    networks:
      - nrm_app_nrm_backend

networks:
  nrm_app_nrm_backend:
    external: true
